name: End-to-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and start all services
        run: docker compose up --build -d

      - name: Wait for application to be ready
        run: |
          until curl -s http://localhost:7777/health | grep "ok"; do
            echo "Waiting for application..."
            sleep 5
          done

      - name: Run Playwright tests
        run: $ docker compose up -d drill-and-practice database && \ 
            docker compose run --rm --entrypoint=npx e2e-playwright playwright test && \
            docker compose rm -sf e2e-playwright

      - name: Stop Docker services
        run: docker-compose down --remove-orphans