on:
  workflow_run:
    workflows: ["deno.yml", "playwright.yml"]
    types:
      - completed
  
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
            
      - name: Set up Render deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -fsSL https://dap-project.onrender.com | bash